repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-byte-order-marker
      - id: check-case-conflict
      - id: check-json
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: check-ast # Is it valid Python?
      # Check for debugger imports and py37+ breakpoint() calls
      # in python source.
      - id: debug-statements
      - id: check-added-large-files

  # - repo: https://github.com/psf/black
  #   rev: 22.6.0
  #   hooks:
  #     - id: black

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.280
    hooks:
      - id: ruff

  # - repo: https://github.com/asottile/seed-isort-config
  #   rev: v2.2.0
  #   hooks:
  #       - id: seed-isort-config # check imports integrity

  # - repo: https://github.com/pre-commit/mirrors-isort
  #   rev: v5.10.1
  #   hooks:
  #       - id: isort

  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v0.971
  #   hooks:
  #       - id: mypy
  #         args: [--ignore-missing-imports]
