repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: fix-byte-order-marker
      - id: check-case-conflict
      - id: check-json
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: check-ast # Is it valid Python?
      # Check for debugger imports and py37+ breakpoint() calls
      # in python source.
      - id: debug-statements
      - id: check-added-large-files

  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        files: "^backend/"

  - repo: https://github.com/python-poetry/poetry
    rev: "1.5.0" # add version here
    hooks:
      - id: poetry-check
      #   args: ["-C", "."]
      #   verbose: true
      - id: poetry-lock
      - id: poetry-export
        args: ["-f", "requirements.txt", "-o", "./requirements.txt", "--without-hashes"]
        verbose: true

  # - repo: https://github.com/astral-sh/ruff-pre-commit
  #   rev: v0.0.280
  #   hooks:
  #     - id: ruff
  #
  # - repo: https://github.com/asottile/seed-isort-config
  #   rev: v2.2.0
  #   hooks:
  #       - id: seed-isort-config # check imports integrity

  # - repo: https://github.com/pre-commit/mirrors-isort
  #   rev: v5.10.1
  #   hooks:
  #       - id: isort

  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v0.971
  #   hooks:
  #       - id: mypy
  #         args: [--ignore-missing-imports]
