name: Testing
on:
  push:
    branches:
      # - main
      - feature

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10.2
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.2
          architecture: x64
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.dev.txt
      - name: Lint with flake8
        run: |
          flake8 . --count --show-source --statistics
      - name: Lint with mypy
        run: |
          mypy
      - name: Test with pytest
        # env:
        #   DBX_KEY: ${{ secrets.DBX_KEY }}
        run: |
          pytest
